#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

[ "$#" -lt 1 ] && { echo >&2 'usage: ejf <file1.java> <file2.java> ...'; exit 3; }

d="$(cd "$(dirname "$0")"; pwd -P)"

cat "$d/lib/sources.list" | grep -Ev '^\s*(#|$)' | while IFS= read -r url ; do
  file="$d/lib/$(echo "$url" | sed -re 's/^.*\/([^\/]+)$/\1/')"
  if [ ! -f "$file" ] ; then
    echo "$url"
    curl -f -L -# -o "$file" "$url" || { rm "$file"; exit 1; }
  fi
done

lib_classpath="$(find "$d/lib/" -name '*.jar' | tr '\n' ':')"

src="$d/src/ejf/Main.java"
bin="$d/bin"
cls="$d/bin/ejf/Main.class"
style="$(find "$d/lib/" -name '*.xml' | head -n 1)"
os="$(uname -o)"

if [ "$os" == "Cygwin" ] ; then
	echo "Setting windows dirs..."
	srcW=src="$(echo "$src" | sed -e 's/\/cygdrive\/\(.\)/\1:\//g')"
	bin="$(echo "$bin" | sed -e 's/\/cygdrive\/\(.\)/\1:\//g')"
	style="$(echo "$style" | sed -e 's/\/cygdrive\/\(.\)/\1:\//g')"
	lib_classpath="$(echo "$lib_classpath" | sed -e 's/:/;/g' -e 's/\/cygdrive\/\(.\)/\1:\//g')"
	args="$(echo "$@" | sed -e 's/\/cygdrive\/\(.\)/\1:\//g')"
	 
	if [ "$src" -nt "$cls" ] ; then
		echo "Recompiling $src ..."
		javac -cp "$lib_classpath" -d "$bin" "$srcW"
		touch -r "$src" "$cls"
	fi

	java -cp "$lib_classpath;$bin" ejf.Main "$style" "$args"
else
	if [ "$src" -nt "$cls" ] ; then
	  echo "Recompiling $src ..."
	  javac -cp "$lib_classpath" -d "$bin" "$src"
	  touch -r "$src" "$cls"
	fi

	java -cp "$lib_classpath:$bin" ejf.Main "$style" "$@"
fi
