#!/bin/sh

root="$(git rev-parse --show-toplevel)"
[ -d "$root" ] || exit 1

owndir="$(dirname "$(readlink -f "$0")")"

find "$owndir"/autoformat -type f -executable | {
  abort=0

  while read formatter ; do
    patterns="$formatter".patterns
    [ -f "$patterns" ] || continue

    git diff --name-only --cached | grep -Eif "$patterns" | {
      labort=0

      while read orig ; do
        orig="${root}/${orig}"
        [ -f "$orig" ] || continue
        "$formatter" "$orig" || labort=1
        git add "$orig"
      done

      exit $labort
    } || abort=1
  done

  exit $abort
}
