#!/bin/sh

owndir="$(dirname "$(readlink -f "$0")")"

git diff --name-only --cached | grep -Ei '\.xml$' |
{
  abort=0

  while read orig ; do
    orig="$(git rev-parse --show-toplevel)/${orig}"
    "$owndir"/autoformat "$orig" || abort=1
    git add "$orig"
  done

  exit $abort
}
